apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  ports:
   - protocol: TCP
     port: 5672 # service port
     targetPort: 5672 # container port
  clusterIP: None # headless service
  selector:
      project: roboshop
      component: rabbitmq
      tier: db    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: db                # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-headless"
  replicas: 1  
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db              #has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        volumeMounts:
        - name: www
          mountPath: /var/lib/rabbitmq
  # PVC
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
