apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    tier: db
spec:
  ports:
  - port:  
    name: redis
  clusterIP: None # headless service
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: db                # has to match .spec.template.metadata.labels
  serviceName: "redis-headless"
  replicas: 1  
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db              #has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: redis:7
        volumeMounts:
        - name: www
          mountPath: /data
  # PVC
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
